language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-android-m2repository
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-license.*'
script: ./gradlew assembleRelease